const data = [
    {
        id: 1,
        patientName: 'Truong Thi Kim Lan',
        date: '22/3/2022',
        time: '7:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 0,
        type: 0,
        status: 2,
    },
    {
        id: 2,
        patientName: 'Diep Thi Thuy Linh',
        date: '22/3/2022',
        time: '9:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 0,
        type: 0,
        status: 0,
    },
    {
        id: 3,
        patientName: 'Truong Thi Thuy Trung',
        date: '22/3/2022',
        time: '10:30',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 0,
        type: 0,
        status: 1,
    },
    {
        id: 4,
        patientName: 'Nguyen Mai Quoc Trung',
        date: '22/3/2022',
        time: '13:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
    {
        id: 5,
        patientName: 'Le Nguyen Sao Mai',
        date: '24/3/2022',
        time: '9:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 0,
        type: 0,
        status: 1,
    },
    {
        id: 6,
        patientName: 'Hoang Van Chuong',
        date: '24/3/2022',
        time: '10:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
    {
        id: 7,
        patientName: 'Mai Nguyen Duc Tho',
        date: '24/3/2022',
        time: '14:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
    {
        id: 8,
        patientName: 'Le Huynh',
        date: '24/3/2022',
        time: '7:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
    {
        id: 9,
        patientName: 'Truong Thi Kim Dung',
        date: '26/3/2022',
        time: '10:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
    {
        id: 10,
        patientName: 'Truong Thi Kim Dung',
        date: '26/3/2022',
        time: '16:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 0,
        type: 0,
        status: 1,
    },
    {
        id: 11,
        patientName: 'Truong Thi Kim Dung',
        date: '26/3/2022',
        time: '15:15',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 0,
        type: 0,
        status: 1,
    },
    {
        id: 12,
        patientName: 'Truong Thi Kim Dung',
        date: '26/3/2022',
        time: '8:30',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
    {
        id: 13,
        patientName: 'Truong Thi Kim Dung',
        date: '21/3/2022',
        time: '7:45',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
    {
        id: 14,
        patientName: 'Truong Thi Kim Dung',
        date: '21/3/2022',
        time: '9:45',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
    {
        id: 15,
        patientName: 'Truong Thi Kim Dung',
        date: '22/3/2022',
        time: '14:45',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
    {
        id: 16,
        patientName: 'Truong Thi Kim Dung',
        date: '24/3/2022',
        time: '15:45',
        doctor: 'Truong Quoc Bao',
        phone: '0123456789',
        gender: 1,
        type: 0,
        status: 1,
    },
];
export default data;
